import file_read
import excel_print
from easygui import msgbox
import traceback
import os

#datalog_path = './B5_andy/'
datalog_path = './Datalog/'

def run_with_file_check(path):
    file_list = os.listdir(path)
    if len(file_list) > 4:
        msgbox("More than 4 files are detected, may cause wrong result! please keep these 4 files only related to this checkout:\n"
               "1. NNT datalog\n"
               "2. trim generator results(if need trim check)\n"
               "3. CFL log\n"
               "4. Config file generated by GUI tool")
    else:
        try:
            file_read_class = file_read.FileReadClass(datalog_path)
        except Exception as Error_print:
            msgbox("Cannot find 3 datalogs. Please double check the MT datalog. \n "
                   "Please send email to jason.chen/Maurice.Mao/jihyun.nam@wdc.com if you cannot fix the issue \n\n"
                   "Error code: \n" + str(traceback.format_exc()),
                   title="Error")
        # print(2)
        try:
            file_read_class.read_mt_datalog()
        except Exception as Error_print:

            msgbox("MT datalog read error. Please double check the MT datalogs. \n" +
                   "Please send email to jason.chen/Maurice.Mao/jihyun.nam@wdc.com if you cannot fix the issue \n\n"
                   "Error code: \n" + str(traceback.format_exc()),
                   title="Error")
        # print(3)
        # file_read_class.read_trim_table()
        try:
            file_read_class.read_trim_table()
        except Exception as Error_print:
            msgbox("Trim table read error. Please double check the Trim table. \n" +
                   "Please send email to jason.chen/Maurice.Mao/jihyun.nam@wdc.com if you cannot fix the issue \n\n"
                   "Error code: \n" + str(traceback.format_exc()),
                   title="Error")
        # print(4)
        # file_read_class.read_llt_datalog()
        try:
            file_read_class.read_llt_datalog()
        except Exception as Error_print:
            msgbox("NanoNT datalog read error. Please double check the Nanont datalog. \n" +
                   "Please send email to jason.chen/Maurice.Mao/jihyun.nam@wdc.com if you cannot fix the issue \n\n"
                   "Error code: \n" + str(traceback.format_exc()),
                   title="Error")
        # print(5)
        try:
            # excel print
            excel_print_class = excel_print.ExcelPrint(file_read_class)
            # print(6)
            excel_print_class.excel_exec()
        except Exception as Error_print:
            msgbox("Excel print error.\n" +
                   "Please send email to jason.chen/Maurice.Mao/jihyun.nam@@wdc.com \n\n"
                   "Error code: \n" + str(traceback.format_exc()),
                   title="Error")


# Make to EXE
# "C:\Users\19981\AppData\Local\Programs\Python\Python38\python.exe" "C:\Users\19981\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe" C:\Users\19981\PycharmProjects\MT_single_package_checkout_JHN\main.py --windowed --onefile
# jason: add trim gen in tha main function
# try:
#     trimtable_generation.run_trim_gen()
# except Exception as trim_gen_error:
#     msgbox("Trim Gen Error!")
# file read and grab data
# print(1)
run_with_file_check(datalog_path)


